# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.6.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pylint
        run: |
          # list out files that are in directory and working tree
          # grep -v will exclude the files being considered for pylint
          # grep -E will matches files having .py extension
          # This command will help to pass required python files to pylint along with pylint_djanog plugin
          # Pylint with -E option will display only if there is any error
          git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' |
            xargs pylint --load-plugins=pylint_django
      - name: Test 
        run: |
          pytest
